# Generated by Django 4.2.23 on 2025-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeekeyresult",
            name="progress_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("%", "Percentage"),
                    ("#", "Number"),
                    ("Currency", (("$", "USD$"), ("₹", "INR"), ("€", "EUR"))),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalemployeekeyresult",
            name="progress_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("%", "Percentage"),
                    ("#", "Number"),
                    ("Currency", (("$", "USD$"), ("₹", "INR"), ("€", "EUR"))),
                ],
                max_length=60,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalkeyresult",
            name="progress_type",
            field=models.CharField(
                choices=[
                    ("%", "Percentage"),
                    ("#", "Number"),
                    ("Currency", (("$", "USD$"), ("₹", "INR"), ("€", "EUR"))),
                ],
                default="%",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="keyresult",
            name="progress_type",
            field=models.CharField(
                choices=[
                    ("%", "Percentage"),
                    ("#", "Number"),
                    ("Currency", (("$", "USD$"), ("₹", "INR"), ("€", "EUR"))),
                ],
                default="%",
                max_length=60,
            ),
        ),
    ]
