# Generated by Django 4.2.23 on 2025-12-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.RemoveField(
            model_name="project",
            name="document",
        ),
        migrations.RemoveField(
            model_name="project",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="document",
        ),
        migrations.RemoveField(
            model_name="task",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="start_date",
        ),
        migrations.AddField(
            model_name="task",
            name="story_point",
            field=models.IntegerField(default=0, verbose_name="Story Point"),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("ongoing", "Ongoing"),
                    ("to_do", "To Do"),
                    ("in_progress", "In Progress"),
                    ("code_review", "Code Review"),
                    ("completed", "Done & Will not do"),
                ],
                default="to_do",
                max_length=250,
                verbose_name="Status",
            ),
        ),
    ]
