# Generated by Django 6.0 on 2025-12-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workrecords',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
